services:
  rss-telegram-bot:
    image: ghcr.io/samueleoraziodurante/rss-telegram:erai-anime
    container_name: rss-telegram
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data